name: levy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  animated_text_kit: ^4.2.1
  flutter_local_notifications: ^9.5.3+1
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.4
  timezone: ^0.8.0
  auto_size_text: ^3.0.0
  sizer: ^2.0.15
  syncfusion_flutter_charts: 19.4.50
  custom_radio_grouped_button: ^2.1.2
  url_launcher: ^6.1.2
  month_year_picker: ^0.2.0+1




dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.11

flutter: 
  uses-material-design: true
  assets:
    - assets/ 
    - assets/wallet-front.png 

  fonts:
    - family: MyFlutterApp
      fonts:
       - asset: assets/MyFlutterApp.ttf
    - family: Money
      fonts:
        - asset: assets/Money.ttf